### ISSUE TITLE
Warning. Client is fake and cannot be targeted

### ISSUE THREAD

**Issue by IL0co** [KoNLiG/customweapons#4]
### To produce
Give the bot a weapon with a modified sound, or the bot can pick up such a weapon.

### The error text
```
L 07/29/2022 - 20:58:18: [SM] Exception reported: Client 8 is fake and cannot be targeted
L 07/29/2022 - 20:58:18: [SM] Blaming: customweapons.smx
L 07/29/2022 - 20:58:18: [SM] Call stack trace:
L 07/29/2022 - 20:58:18: [SM]   [0] ConVar.ReplicateToClient
L 07/29/2022 - 20:58:18: [SM]   [1] Line 56, customweapons\structs.sp::ToggleDefaultShotSounds
L 07/29/2022 - 20:58:19: [SM]   [2] Line 70, customweapons\soundsmgr.sp::Timer_ToggleDefaultSounds
```

**Comment by KoNLiG** [comment]
First of all thank you for taking some time and reporting this issue.

I've thought about disabling the whole custom weapon system when it comes to fake clients, 
but I ended up allowing custom weapon to fake clients with the client sided weapon sound disabled.
