### ISSUE TITLE
AddSoundHook and AddModelHook do not work

### ISSUE THREAD

**Issue by eyal282** [KoNLiG/customweapons#7]
Not only do they not fire, AddSoundHook is a missing native from the main plugin.

I tried fixing it, but I can't say I'm finding success.

Edit: Got it to work, but I feel like the .SetModel is redundant as a **mandatory action to make it work.**

```
public void OnEntityCreated(int entity, const char[] classname)
{
	if(StrEqual(classname, "weapon_m4a1"))
	{
		SDKHook(entity, SDKHook_SpawnPost, OnWeaponSpawn);
	}
}

public void OnWeaponSpawn(int entity)
{
	CustomWeapon cWeapon = CustomWeapon(entity);

	cWeapon.SetModel(CustomWeaponModel_View, "");
	cWeapon.AddModelHook(OnShouldCrossbowModel);

	PrintToChatAll("bded");
}
```

Edit 2: This netprops has a sinister effect that I'll attempt to hopefully address.
When its set, EVERY SINGLE M4A1 YOU GET FOR THE REST OF THE ROUND WILL BE THE CROSSBOW, unless you switch to another non-m4a1 weapon. This can be extremely problematic in LRs, when you literally have no other weapon to switch to.
The solution is either some refresh function, or when the crossbow is destroyed, give the player a knife, switch to it, kill the knife.

Edit 3: Theoretical fix here: https://github.com/eyal282/csgo-jailbreak-package/tree/master/addons/sourcemod/scripting/customweapons
There was also an issue with checking validations without even acknowledging the model / sound given from the hook.

**Comment by KoNLiG** [comment]
Since this issue is really unclear about what's the actual issue in the field, it has been closed.
